### ISSUE TITLE
Don't publish individual paths

### ISSUE THREAD

**Issue by tkurki** [itemir/signalk-activecaptain#1]
https://github.com/itemir/signalk-activecaptain/blob/963d2d435bb5cfda936b44f7e02f16a2c83a8588/index.js#L88

This makes the data needlessly complex - the data is a "soup" of individual values, that any consuming code needs to parse and stitch together.
<img width="1040" alt="image" src="https://github.com/itemir/signalk-activecaptain/assets/1049678/598c5dca-16cc-4593-bf72-aacd7b1043bd">

<img width="706" alt="image" src="https://github.com/itemir/signalk-activecaptain/assets/1049678/f27938da-b404-4c8a-95b5-7373a0f757f7">

A poi's data should be one object, as the values are not data fields that update independently.

```
    app.handleMessage(plugin.id, {
      updates: [
        {
          values: [
            {
              path: `${poiKey}.${poi.id}`,
              value: poi
            }
          ]
        }
      ]
    })
```

**Comment by itemir** [comment]
Changed. I think we should put some best practices in the plugin development guide with examples.
